# Generated by Django 5.2.7 on 2025-11-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_historialguia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialguia',
            old_name='titulo_guia',
            new_name='numero_guia',
        ),
        migrations.AddField(
            model_name='historialguia',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historialguia',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialguia',
            name='hora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialguia',
            name='sucursal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
