# Generated by Django 5.2.7 on 2025-11-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_titulo_guia_historialguia_numero_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialguia',
            name='consulta_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, default='Mi biografía.', max_length=500),
        ),
    ]
