# Generated by Django 5.2.8 on 2025-11-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_historialguia_consulta_id_alter_perfil_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialguia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
