# Generated by Django 6.0.4 on 2026-05-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_sprint4_sprint5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialguia',
            name='activo',
        ),
    ]
