# Generated by Django 6.0.4 on 2026-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_historialguia_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialguia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
